var annotated_dup =
[
    [ "std", null, [
      [ "hash< std::filesystem::path >", "structstd_1_1hash_3_01std_1_1filesystem_1_1path_01_4.html", "structstd_1_1hash_3_01std_1_1filesystem_1_1path_01_4" ]
    ] ],
    [ "ui", null, [
      [ "Button", "classui_1_1_button.html", "classui_1_1_button" ],
      [ "Label", "classui_1_1_label.html", "classui_1_1_label" ],
      [ "Menu", "classui_1_1_menu.html", "classui_1_1_menu" ],
      [ "Widget", "classui_1_1_widget.html", "classui_1_1_widget" ],
      [ "Window", "classui_1_1_window.html", "classui_1_1_window" ]
    ] ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "ClearFlag", "struct_clear_flag.html", null ],
    [ "CommandBuffer", "class_command_buffer.html", "class_command_buffer" ],
    [ "CommandQueue", "class_command_queue.html", "class_command_queue" ],
    [ "DDSHeader", "struct_d_d_s_header.html", "struct_d_d_s_header" ],
    [ "DDSHeaderDXT10", "struct_d_d_s_header_d_x_t10.html", "struct_d_d_s_header_d_x_t10" ],
    [ "DDSPixelFormat", "struct_d_d_s_pixel_format.html", "struct_d_d_s_pixel_format" ],
    [ "Gamepad", "class_gamepad.html", "class_gamepad" ],
    [ "GLCmdClear", "struct_g_l_cmd_clear.html", "struct_g_l_cmd_clear" ],
    [ "GLCmdDraw", "struct_g_l_cmd_draw.html", "struct_g_l_cmd_draw" ],
    [ "GLCmdDrawIndexed", "struct_g_l_cmd_draw_indexed.html", "struct_g_l_cmd_draw_indexed" ],
    [ "GLCmdSetClearColor", "struct_g_l_cmd_set_clear_color.html", "struct_g_l_cmd_set_clear_color" ],
    [ "GLCmdSetClearDepth", "struct_g_l_cmd_set_clear_depth.html", "struct_g_l_cmd_set_clear_depth" ],
    [ "GLCmdSetIndexBuffer", "struct_g_l_cmd_set_index_buffer.html", "struct_g_l_cmd_set_index_buffer" ],
    [ "GLCmdSetPipeline", "struct_g_l_cmd_set_pipeline.html", "struct_g_l_cmd_set_pipeline" ],
    [ "GLCmdSetVertexBuffer", "struct_g_l_cmd_set_vertex_buffer.html", "struct_g_l_cmd_set_vertex_buffer" ],
    [ "GLCmdSetViewport", "struct_g_l_cmd_set_viewport.html", "struct_g_l_cmd_set_viewport" ],
    [ "GLCommandBuffer", "class_g_l_command_buffer.html", "class_g_l_command_buffer" ],
    [ "GLCommandQueue", "class_g_l_command_queue.html", "class_g_l_command_queue" ],
    [ "GLIndexBuffer", "class_g_l_index_buffer.html", "class_g_l_index_buffer" ],
    [ "GLProgram", "class_g_l_program.html", "class_g_l_program" ],
    [ "GLRenderer", "class_g_l_renderer.html", "class_g_l_renderer" ],
    [ "GLShader", "class_g_l_shader.html", "class_g_l_shader" ],
    [ "GLTexture", "class_g_l_texture.html", "class_g_l_texture" ],
    [ "GLVertexArray", "class_g_l_vertex_array.html", "class_g_l_vertex_array" ],
    [ "GLVertexBuffer", "class_g_l_vertex_buffer.html", "class_g_l_vertex_buffer" ],
    [ "Image", "class_image.html", "class_image" ],
    [ "IndexBuffer", "class_index_buffer.html", "class_index_buffer" ],
    [ "Input", "class_input.html", null ],
    [ "Material", "class_material.html", "class_material" ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "Model", "class_model.html", "class_model" ],
    [ "Monitor", "class_monitor.html", "class_monitor" ],
    [ "OrthographicCamera", "class_orthographic_camera.html", "class_orthographic_camera" ],
    [ "PerspectiveCamera", "class_perspective_camera.html", "class_perspective_camera" ],
    [ "Pipeline", "class_pipeline.html", "class_pipeline" ],
    [ "Program", "class_program.html", "class_program" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "RID", "class_r_i_d.html", "class_r_i_d" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "UI", "class_u_i.html", null ],
    [ "VertexBuffer", "class_vertex_buffer.html", "class_vertex_buffer" ],
    [ "VertexFormat", "class_vertex_format.html", "class_vertex_format" ],
    [ "VKCommandBuffer", "class_v_k_command_buffer.html", "class_v_k_command_buffer" ],
    [ "VKCommandQueue", "class_v_k_command_queue.html", "class_v_k_command_queue" ],
    [ "VKProgram", "class_v_k_program.html", "class_v_k_program" ],
    [ "VKRenderer", "class_v_k_renderer.html", "class_v_k_renderer" ],
    [ "VKShader", "class_v_k_shader.html", "class_v_k_shader" ],
    [ "Window", "class_window.html", "class_window" ]
];