# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Graphics_config = debug
  Triangle_config = debug
  Test_config = debug
  glad_config = debug
  glfw_config = debug
  assimp_config = debug
  meshoptimizer_config = debug

else ifeq ($(config),release)
  Graphics_config = release
  Triangle_config = release
  Test_config = release
  glad_config = release
  glfw_config = release
  assimp_config = release
  meshoptimizer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Graphics Triangle Test glad glfw assimp meshoptimizer

.PHONY: all clean help $(PROJECTS) Deps Examples

all: $(PROJECTS)

Deps: assimp glad glfw meshoptimizer

Examples: Test Triangle

Graphics: glad glfw assimp meshoptimizer
ifneq (,$(Graphics_config))
	@echo "==== Building Graphics ($(Graphics_config)) ===="
	@${MAKE} --no-print-directory -C Source -f Makefile config=$(Graphics_config)
endif

Triangle: Graphics
ifneq (,$(Triangle_config))
	@echo "==== Building Triangle ($(Triangle_config)) ===="
	@${MAKE} --no-print-directory -C Examples/Triangle -f Makefile config=$(Triangle_config)
endif

Test: Graphics
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C Examples/Test -f Makefile config=$(Test_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Deps -f glad.make config=$(glad_config)
endif

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C Deps -f glfw.make config=$(glfw_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C Deps -f assimp.make config=$(assimp_config)
endif

meshoptimizer:
ifneq (,$(meshoptimizer_config))
	@echo "==== Building meshoptimizer ($(meshoptimizer_config)) ===="
	@${MAKE} --no-print-directory -C Deps -f meshoptimizer.make config=$(meshoptimizer_config)
endif

clean:
	@${MAKE} --no-print-directory -C Source -f Makefile clean
	@${MAKE} --no-print-directory -C Examples/Triangle -f Makefile clean
	@${MAKE} --no-print-directory -C Examples/Test -f Makefile clean
	@${MAKE} --no-print-directory -C Deps -f glad.make clean
	@${MAKE} --no-print-directory -C Deps -f glfw.make clean
	@${MAKE} --no-print-directory -C Deps -f assimp.make clean
	@${MAKE} --no-print-directory -C Deps -f meshoptimizer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Graphics"
	@echo "   Triangle"
	@echo "   Test"
	@echo "   glad"
	@echo "   glfw"
	@echo "   assimp"
	@echo "   meshoptimizer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"