name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest
        arch: [x64, x86, arm64, arm]
        include:
        - os: windows-latest
          cmake_install_deps: ./Scripts/cmake_install_deps.bat
          make_build: ./Scripts/cmake_build.bat

        # - os: ubuntu-latest
        #   cmake_install_deps: ./Scripts/cmake_install_deps.sh
        #   cmake_build: ./Scripts/cmake_build.sh

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSVC Developer Command Environment
        if: ${{matrix.os == 'windows-latest'}}
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Install dependencies
        run: ${{matrix.cmake_install_deps}}

      - name: Build
        run: ${{matrix.cmake_build}}

      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: graphics-${{matrix.arch}}
          path: build/${{env.prog_name}}/lib

      - name: Upload bins
        uses: actions/upload-artifact@v2
        with:
          name: examples-${{matrix.arch}}
          path: build/${{env.prog_name}}/bin
