name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest
        arch: [x64, x86, arm, arm64]
        # compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./Scripts/cmake_build.bat

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/${{env.prog_name}}
