name: macOS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: macos-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Cache vcpkg artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/.git
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: macos-${{ matrix.type }}-${{ matrix.arch }}-${{ hashFiles('vcpkg.json') }}

      # - name: Install dependencies
      #   run: vcpkg install

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: macos-${{ matrix.type }}-${{ matrix.arch }}

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v3
        with:
          name: graphics-macos-${{ matrix.arch }}
          path: build/lib/libgraphics.a

      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: examples-macos-${{ matrix.arch }}
          path: build/bin/*/*
