name: MacOS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        config: [Debug, Release]

    runs-on: macos-latest
    name: ${{ matrix.config }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./Scripts/cmake_install_deps.sh

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.config }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: graphics-macos-${{ matrix.arch }}
          path: build/lib

      - name: Upload bins
        uses: actions/upload-artifact@v2
        with:
          name: examples-macos-${{ matrix.arch }}
          path: build/bin
