name: macOS

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos.yml'

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: macos-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ./build
          key: macos-${{ matrix.type }}-${{ matrix.arch }}

      - name: Install dependencies
        run: ./Scripts/cmake_install_deps.sh

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: graphics-macos-${{ matrix.arch }}
          path: build/lib

      - name: Upload bins
        uses: actions/upload-artifact@v2
        with:
          name: examples-macos-${{ matrix.arch }}
          path: build/bin
