name: macOS

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.sh'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.sh'
      - '.github/workflows/macos.yml'

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: macos-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Cache vcpkg artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.VCPKG_ROOT }}
            ${{ github.workspace }}/vcpkg_installed
            !${{ env.VCPKG_ROOT }}/.git
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: macos-${{ matrix.type }}-${{ matrix.arch }}-${{ hashFiles('vcpkg.json') }}

      - name: Install dependencies
        run: vcpkg install

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ./build
          key: macos-${{ matrix.type }}-${{ matrix.arch }}

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: graphics-macos-${{ matrix.arch }}
          path: build/lib

      - name: Upload bins
        uses: actions/upload-artifact@v2
        with:
          name: examples-macos-${{ matrix.arch }}
          path: build/bin
