name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: ubuntu-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    env:
      VCPKG_ROOT: '/usr/local/share/vcpkg'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: 13

      - name: Cache vcpkg artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/.git
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: ubuntu-${{ matrix.type }}-${{ matrix.arch }}-${{ hashFiles('vcpkg.json') }}

      - name: Install dependencies
        run: vcpkg install

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ubuntu-${{ matrix.type }}-${{ matrix.arch }}

      - name: Generating CMake cache
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v3
        with:
          name: graphics-ubuntu-${{ matrix.arch }}
          path: build/lib/libgraphics.a

      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: examples-ubuntu-${{ matrix.arch }}
          path: build/bin/*/*
