name: Ubuntu

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.sh'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.sh'
      - '.github/workflows/ubuntu.yml'

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: ubuntu-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: 13

      - name: Install dependencies
        run: ./Scripts/cmake_install_deps.sh

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ./build
          key: ubuntu-${{ matrix.type }}-${{ matrix.arch }}

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: graphics-ubuntu-${{ matrix.arch }}
          path: build/lib

      - name: Upload bins
        uses: actions/upload-artifact@v2
        with:
          name: examples-ubuntu-${{ matrix.arch }}
          path: build/bin
