name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: ubuntu-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    env:
      VCPKG_ROOT: '/usr/local/share/vcpkg'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: 13

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Build
        run: ./Scripts/build.sh ${{ matrix.type }} clang 13

      - name: Upload libs
        uses: actions/upload-artifact@v3
        with:
          name: graphics-ubuntu-${{ matrix.type }}-${{ matrix.arch }}
          path: build/lib/libgraphics.a

      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: examples-ubuntu-${{ matrix.type }}-${{ matrix.arch }}
          path: build/bin/*/*
