name: Windows

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.bat'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.bat'
      - '.github/workflows/windows.yml'

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: windows-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    env:
      VCPKG_ROOT: 'C:/vcpkg'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: 13

      - name: Cache vcpkg artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/.git
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          key: windows-${{ matrix.type }}-${{ matrix.arch }}-${{ hashFiles('vcpkg.json') }}

      # - name: Setup MSVC Developer Command Environment
      #   uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: windows-${{ matrix.type }}-${{ matrix.arch }}

      - name: Generating CMake cache
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_COMPILER=clang -DCMAKE_C_COMPILER=clang

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: graphics-windows-${{ matrix.arch }}
          path: |
            build/**/graphics.lib
            build/**/graphicsd.lib

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: examples-windows-${{ matrix.arch }}
          path: |
            build/bin/**/*.exe
            build/bin/**/*.glsl
            !build/bin/Debug
            !build/bin/Release
