name: Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: windows-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    env:
      VCPKG_ROOT: 'C:/vcpkg'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Setup MSVC Developer Command Environment
      #   uses: ilammy/msvc-dev-cmd@v1.10.0

      # - name: Install clang
      #   uses: egor-tensin/setup-clang@v1.3
      #   with:
      #     version: 13

      - name: Install dependencies
        run: ./Scripts/cmake_install_deps.bat

      - name: Generating CMake cache
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j8

      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: graphics-windows-${{ matrix.arch }}
          path: |
            build/**/graphics.lib
            build/**/graphicsd.lib

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: examples-windows-${{ matrix.arch }}
          path: |
            build/bin/**/*.exe
            build/bin/**/*.glsl
            !build/bin/Debug
            !build/bin/Release
