name: Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]
        include:
          - type: Debug
            vs_args: MTd
          - type: Release
            vs_args: MT

    runs-on: windows-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    env:
      VCPKG_ROOT: 'C:/vcpkg'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Setup MSVC Developer Command Environment
      #   uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Build
        run: ./scripts/build.bat ${{ matrix.type }}

      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: graphics-windows-${{ matrix.type }}-${{ matrix.arch }}
          path: |
            build/**/graphics.lib
            build/**/graphicsd.lib

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: examples-windows-${{ matrix.type }}-${{ matrix.arch }}
          path: |
            build/bin/**/*.exe
            build/bin/**/*.glsl
            !build/bin/Debug
            !build/bin/Release
