name: Windows

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.bat'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - 'Scripts/vcpkg_install_deps.bat'
      - '.github/workflows/windows.yml'

jobs:
  build:
    strategy:
      matrix:
        arch: [x64] # arm64
        type: [Debug, Release]

    runs-on: windows-latest
    name: ${{ matrix.type }}-${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: 13

      - name: Cache vcpkg artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/vcpkg_installed
            # ${{ env.VCPKG_ROOT }}
            # !${{ env.VCPKG_ROOT }}/.git
            # !${{ env.VCPKG_ROOT }}/buildtrees
            # !${{ env.VCPKG_ROOT }}/packages
            # !${{ env.VCPKG_ROOT }}/downloads
          key: windows-${{ matrix.type }}-${{ matrix.arch }}-${{ hashFiles('vcpkg.json') }}

      # - name: Install dependencies
      #   run: vcpkg install

      # - name: Setup MSVC Developer Command Environment
      #   uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ./build
          key: windows-${{ matrix.type }}-${{ matrix.arch }}

      - name: Test
        run: del build

      - name: Generating CMake cache
        run: cmake -B build -T clang

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: graphics-windows-${{ matrix.arch }}
          path: build/lib

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: examples-windows-${{ matrix.arch }}
          path: build/bin
